### ISSUE TITLE
PCB in release section uses wrong/non-existing parts

### ISSUE THREAD

**Issue by Nobodi99** [Bastardkb/charybdis-pmw-sensor#2]
I am in the process of ordering the sensor pcb with the files provided in the release section.
There are some problems with the parts used and the files provided .

1) The parts used are metric 0603 but jlcpcb uses imperial code in their systems. That means the parts don't fit and trying to find replacements is not possible because there are no 0603/0201 10uF capacitors. And the other parts are non standard which makes them way more expensive because of the extra charge.

2) The cpl file places the parts outside the pcb and the orientation is wrong on some parts.

That means that those files are basically useless and need to be fixed in my opinion.

**Comment by bstiq** [comment]
Hello,

1/ I've had no issue ordering the PCBs on JLC, and had multiple reports of it working well for others. So the 0603 parts will work fine.
I used whichever parts I found best, standard or not. The PCBs still come out at around 4-5 eur per unit if you order 10 of them or so iirc.

2/ This happens frequently with JLC, they will correct it. Just make sure the orientation is correct on the parts - they tend to place the level shifter rotated wrong.

I'm sorry you find the files useless, feel free to push a PR with the fixes you proposed !
Meanwhile, I will close this issue.

Regards,

**Comment by Nobodi99** [comment]
Thanks for fixing the file.
Before your new upload it was 1.6pre1.zip and that had the smaller parts and was therefore not usable.
The 1.6e.zip has bigger pads and is correct for the 0603 parts size.
Would have been nice of you to at least say that you fixed it instead of just saying it worked for you...

**Comment by bstiq** [comment]
Hey, 

The other files were in testing, which I confirmed working. Just forgot to update the release.
This is also a kind reminder that this is an open source project that is provided as is, and I have no obligation to it or you.
Acting entitled is not helpful.

Regards,
