### ISSUE TITLE
Question about TXS0104EDR

### ISSUE THREAD

**Issue by superjax** [Bastardkb/charybdis-pmw-sensor#3]
Hey!  Thank you for putting this online.  I really appreciate the work here.

It looks like the `master` version of the code is using a different footprint part for the voltage-level translator than what's 
called out in the README (and also the kicad files, I'm not mistaken).  

What part are you using there, or can you point me to the `TXS0104EDR` that has the right footprint?

**Comment by bstiq** [comment]
Hello,

The latest release and master branch now use PCB assembly only.
If you are going to DIY, use the BOM from the readme and the gerber files from release 1.51.
If you are going to PCBA, use the gerber and BOM, POS files from the latest release (1.7).

I will close this now, but feel free to reopen if there's anything else.
