### ISSUE TITLE
AP7331-20WG-7

### ISSUE THREAD

**Issue by GeekAnnoyed** [Bastardkb/charybdis-pmw-sensor#8]
Hello
sorry I'm still a noob with electronics

I'm thinking of using this as a sensor for my keyboard trackball
but I'm having issues getting the AP7331-20WG-7 without incurring a crazy shipping fee (over £9 for a sub £2 order)
is the an alternate regulator I could use?

many thanks

**Comment by bstiq** [comment]
Hello,

That is usually the issue when ordering the components separately yes.
I order those factory-assembled now, so can't recommend any other shop source.

You could also get an ap7331-wg-7, but then make sure to install R2 and R3 as you'll need those to indicate the required output voltage.

Finally, another option is to just look for 2V voltage regulators. You can use different website's search engines for that (mouser, farnell, radiospare all have voltage regulator sections)

When choosing, pay attention to:
- the format of the component
- the pinout which needs to be the same
- the current output - if the regulator can't supply enough current the sensor will not work
Regarding the last issue, I had exactly this problem and it induced a bad coil whine (although with another regulator). I talk about it here: https://www.youtube.com/watch?v=xcH720h-YqM

The part number mentioned in the BOM is the only one I tested, so I can't vouch / guarantee for any other ones.

If you are a newcomer with electronics and also with soldering, then I recommend paying a bit extra and ordering the assembled version from eg. JLCPCB. Soldering the components of the DIY version is difficult and you *will* encounter issues where the sensor doesn't work and it's impossible to figure out why (speaking from experience).

I hope this helps !

Regards,

**Comment by GeekAnnoyed** [comment]
*hides face in geek shame*

I honestly didn't look at JLCPCB as during my last project with a different PCB manufacturer I almost choked on my coffee when I got a quote for the component assembly too.

I'm not too bad at soldering, not awesome but bad it's the design part I fail with.

But thank you for the JLCPCB advice.

I will close this when I get home again

Regards
Richard
