### ISSUE TITLE
PMW3360DM-T2QU not avaliable

### ISSUE THREAD

**Issue by Kulllerkeks** [Bastardkb/charybdis-pmw-sensor#9]
Hey!

At first thanks for the work! Im currently wrapping my head around building a Charybdis nano.

I was clicking trough a jlcpcb order to get the senor manufactured and assembled but it seems  PMW3360DM-T2QU is not available?

 I cant find the part even in the parts management of jlcpcb. 

Is this a recent change? Or should i order from a different service?

thanks in advance! love your work.

**Comment by Kulllerkeks** [comment]
i may be dump.
i need to source the part myself am i right?

**Comment by bstiq** [comment]
Yes, and handsolder it (it's pretty easy).
Make sure to get the exact reference (PMW3360), other versions have different pinout and won't work (eg. 3610).

**Comment by Kulllerkeks** [comment]
tanks a lot!
